name: Build golang executable on PR

on:
  pull_request_target:

jobs:
  golang-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os:
          - linux
          - windows
          - darwin
        arch:
          - amd64
    steps:
      - uses: thetillhoff/action-golang-build@b94bf8d46bc2dd0f7324fcbd0c6530838943976e # v1.1.0
        with:
          OS: "${{ matrix.os }}"
          ARCH: "${{ matrix.arch }}"
